force-app/main/default/objects/Answer__c/fields/Count_Vote__c.field-meta.xml
<CustomField>
    <fullName>Count_Vote__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Vote</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Is_Best_Answer__c.field-meta.xml
<CustomField>
    <fullName>Is_Best_Answer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Best Answer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/AnswerHandler.cls
public class AnswerHandler extends TriggerHandler {
    public override void afterUpdate(){
        
    }
    public override void beforeUpdate(){
        checkRating((List<Answer__c>) newList);
    }
    public override void afterInsert(){
        
    }
    public override void beforeInsert(){
        
    }
   //---------------------------------------------------------------------------------------------------------------//
   
    public static void checkRating(List<Answer__c> newAnswers){
        for(Answer__c eachAnswer : newAnswers){
            if(eachAnswer.Is_Best_Answer__c){
                eachAnswer.Rating__c = 3;
            }
            else if(eachAnswer.Count_Vote__c <= 0 ){
                eachAnswer.Rating__c = 0;                
            }
            else if(eachAnswer.Count_Vote__c < 3){
                eachAnswer.Rating__c = 1;                
            }
            else if(eachAnswer.Count_Vote__c < 5){
                eachAnswer.Rating__c = 2;                
            }
            else{
                eachAnswer.Rating__c = 3;  
            }
        }
    } 
}