force-app/main/default/objects/Answer__c/fields/Count_Vote__c.field-meta.xml
<CustomField>
    <fullName>Count_Vote__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Count Vote</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Is_Best_Answer__c.field-meta.xml
<CustomField>
    <fullName>Is_Best_Answer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Best Answer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Answer__c/fields/Rating__c.field-meta.xml
<CustomField>
    <fullName>Rating__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Rating</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Question__c/fields/Best_Answer__c.field-meta.xml
<CustomField>
    <fullName>Best_Answer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Best Answer</label>
    <referenceTo>Answer__c</referenceTo>
    <relationshipLabel>Questions</relationshipLabel>
    <relationshipName>Questions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/QuestionAnswer.cls
public class QuestionAnswer {
    
    @AuraEnabled(cacheable = true)
    public static List<Question__c> getQuestionAnswers(){
        return [SELECT Id,CreatedById, Description__c,Best_Answer__c, (SELECT Id,Name,Description__c,CreatedById,Question__c,Is_Best_Answer__c,Rating__c,Count_Vote__c FROM Answers__r order by Rating__c desc,createddate desc) FROM 
                Question__c];
    }
    
    @AuraEnabled
    public static void submitAnswer(Id questionId, String answer){
        Answer__c userAnswer = new Answer__c(Question__c = questionId,Name = answer,Description__c = answer); 
        insert userAnswer;
    }

    @AuraEnabled
    public static void submitBestAnswer(Id questionId, Id answer){
        Question__c bestQuestionAnswer = new Question__c(Id = questionId,Best_Answer__c = answer);        
        update bestQuestionAnswer;
        Answer__c bestAnswer = new Answer__c(Id = answer,Is_Best_Answer__c = true); 
        update bestAnswer;
    }
    
    @AuraEnabled
    public static void countVote(String voteType,Id answerId){
        Answer__c userAnswer = [SELECT Count_Vote__c FROM Answer__c WHERE ID = :answerId];
        if(voteType.equalsIgnoreCase('Upvote')){
            userAnswer.Count_Vote__c = userAnswer.Count_Vote__c + 1;
        }
        else{
            userAnswer.Count_Vote__c = userAnswer.Count_Vote__c - 1; 
        }
        update userAnswer;
    }    
}